In [34]:
import polars as pl
from polars import col
pl.Config.set_tbl_rows(100)

polars.config.Config

In [47]:
quote_pattern = r"(USDT|BUSD|USDC|EUR|USD|BTC|ETH)$"
path = "/Users/oceansxyz/alphanode-metal/logs/ingest/ingest_20260610_195936.jsonl"

#path = "../datalake/ingest_20260610_181650.jsonl"

In [48]:
df = pl.read_ndjson(path).slice(1)\
    .with_columns(col("log_ts_utc_ms").cast(pl.Datetime("ms")).alias("datetime"))\
    .select('datetime', 'symbol', 'last_update_id', 'best_bid', 'best_bid_qty', 'best_ask', 'best_ask_qty')
   
    #.with_columns([ col("symbol").str.extract(quote_pattern, 1).alias("qoute"), col("symbol").str.replace(quote_pattern, "").alias("base")])

In [49]:
df.head()

shape: (5, 7)
┌──────────────┬──────────┬────────────────┬──────────┬──────────────┬──────────┬──────────────┐
│ datetime     ┆ symbol   ┆ last_update_id ┆ best_bid ┆ best_bid_qty ┆ best_ask ┆ best_ask_qty │
│ ---          ┆ ---      ┆ ---            ┆ ---      ┆ ---          ┆ ---      ┆ ---          │
│ datetime[ms] ┆ str      ┆ i64            ┆ f64      ┆ f64          ┆ f64      ┆ f64          │
╞══════════════╪══════════╪════════════════╪══════════╪══════════════╪══════════╪══════════════╡
│ 2026-06-10   ┆ SUIUSDT  ┆ 15466046426    ┆ 0.7339   ┆ 1506.7       ┆ 0.734    ┆ 2419.6       │
│ 19:59:37.236 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ SUIEUR   ┆ 711817742      ┆ 0.6354   ┆ 56.5         ┆ 0.6355   ┆ 56.5         │
│ 19:59:37.244 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BNBFDUSD ┆ 5397758615     ┆ 589.33   ┆ 0.453        ┆ 589.34   ┆ 0.336        │
│ 19:59:37.292 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCFDUSD ┆ 41923599530    ┆ 62091.93 ┆ 0.01554      ┆ 62091.94 ┆ 0.00483      │
│ 19:59:37.299 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ ETHFDUSD ┆ 28017404787    ┆ 1634.14  ┆ 0.2983       ┆ 1634.15  ┆ 0.0099       │
│ 19:59:37.300 ┆          ┆                ┆          ┆              ┆          ┆              │
└──────────────┴──────────┴────────────────┴──────────┴──────────────┴──────────┴──────────────┘

In [50]:
df.filter(col('symbol').is_in(["BTCUSDT","BTCEURI","EURIUSDT"])).head(20)

shape: (20, 7)
┌──────────────┬──────────┬────────────────┬──────────┬──────────────┬──────────┬──────────────┐
│ datetime     ┆ symbol   ┆ last_update_id ┆ best_bid ┆ best_bid_qty ┆ best_ask ┆ best_ask_qty │
│ ---          ┆ ---      ┆ ---            ┆ ---      ┆ ---          ┆ ---      ┆ ---          │
│ datetime[ms] ┆ str      ┆ i64            ┆ f64      ┆ f64          ┆ f64      ┆ f64          │
╞══════════════╪══════════╪════════════════╪══════════╪══════════════╪══════════╪══════════════╡
│ 2026-06-10   ┆ EURIUSDT ┆ 95042619       ┆ 1.1546   ┆ 588.1        ┆ 1.1547   ┆ 250.0        │
│ 19:59:37.746 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566424133    ┆ 61991.46 ┆ 0.37542      ┆ 61991.47 ┆ 1.04851      │
│ 19:59:38.013 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566425076    ┆ 61991.46 ┆ 0.56827      ┆ 61991.47 ┆ 0.79451      │
│ 19:59:39.015 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ EURIUSDT ┆ 95042620       ┆ 1.1546   ┆ 588.1        ┆ 1.1547   ┆ 250.0        │
│ 19:59:39.746 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566425516    ┆ 61991.46 ┆ 0.43011      ┆ 61991.47 ┆ 0.6328       │
│ 19:59:40.014 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ EURIUSDT ┆ 95042622       ┆ 1.1546   ┆ 588.1        ┆ 1.1547   ┆ 250.0        │
│ 19:59:40.746 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566429284    ┆ 61982.0  ┆ 0.35934      ┆ 61982.01 ┆ 2.80764      │
│ 19:59:41.014 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ EURIUSDT ┆ 95042623       ┆ 1.1546   ┆ 588.1        ┆ 1.1547   ┆ 250.0        │
│ 19:59:41.749 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEURI  ┆ 168478326      ┆ 53683.91 ┆ 0.00018      ┆ 53695.56 ┆ 0.02854      │
│ 19:59:41.779 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566430355    ┆ 61980.0  ┆ 0.0024       ┆ 61980.01 ┆ 1.42719      │
│ 19:59:42.015 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ EURIUSDT ┆ 95042625       ┆ 1.1546   ┆ 588.1        ┆ 1.1547   ┆ 250.0        │
│ 19:59:42.752 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566430612    ┆ 61980.0  ┆ 0.04555      ┆ 61980.01 ┆ 1.42496      │
│ 19:59:43.013 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ EURIUSDT ┆ 95042626       ┆ 1.1546   ┆ 588.1        ┆ 1.1547   ┆ 250.0        │
│ 19:59:43.746 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEURI  ┆ 168478328      ┆ 53683.91 ┆ 0.00018      ┆ 53694.97 ┆ 0.02836      │
│ 19:59:43.778 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566433453    ┆ 61972.0  ┆ 0.05281      ┆ 61972.01 ┆ 1.85539      │
│ 19:59:44.013 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEURI  ┆ 168478329      ┆ 53683.91 ┆ 0.00018      ┆ 53694.97 ┆ 0.02836      │
│ 19:59:44.779 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566434382    ┆ 61972.0  ┆ 0.52579      ┆ 61972.01 ┆ 1.35214      │
│ 19:59:45.013 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ EURIUSDT ┆ 95042628       ┆ 1.1546   ┆ 588.1        ┆ 1.1547   ┆ 250.0        │
│ 19:59:45.747 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566437122    ┆ 61962.0  ┆ 0.0401       ┆ 61962.01 ┆ 1.4044       │
│ 19:59:46.015 ┆          ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT  ┆ 95566438375    ┆ 61962.0  ┆ 0.18641      ┆ 61962.01 ┆ 0.87052      │
│ 19:59:47.014 ┆          ┆                ┆          ┆              ┆          ┆              │
└──────────────┴──────────┴────────────────┴──────────┴──────────────┴──────────┴──────────────┘

In [45]:
df.filter(col('symbol').is_in(["EURUSDT"])).head(20)

shape: (0, 7)
┌──────────────┬────────┬────────────────┬──────────┬──────────────┬──────────┬──────────────┐
│ datetime     ┆ symbol ┆ last_update_id ┆ best_bid ┆ best_bid_qty ┆ best_ask ┆ best_ask_qty │
│ ---          ┆ ---    ┆ ---            ┆ ---      ┆ ---          ┆ ---      ┆ ---          │
│ datetime[ms] ┆ str    ┆ i64            ┆ f64      ┆ f64          ┆ f64      ┆ f64          │
╞══════════════╪════════╪════════════════╪══════════╪══════════════╪══════════╪══════════════╡
└──────────────┴────────┴────────────────┴──────────┴──────────────┴──────────┴──────────────┘