In [1]:
import polars as pl
from polars import col

In [2]:
df = pl.read_ndjson("execution.jsonl")

In [4]:
df.filter(col("ok")==True).head()

shape: (5, 9)
┌───────────────┬───────────────┬────────────┬───────────────┬───┬─────────┬──────┬─────────┬──────┐
│ send_ts_utc_m ┆ response_ts_u ┆ latency_ms ┆ tick_to_trade ┆ … ┆ symbol  ┆ side ┆ qty     ┆ ok   │
│ s             ┆ tc_ms         ┆ ---        ┆ _ms           ┆   ┆ ---     ┆ ---  ┆ ---     ┆ ---  │
│ ---           ┆ ---           ┆ i64        ┆ ---           ┆   ┆ str     ┆ str  ┆ f64     ┆ bool │
│ i64           ┆ i64           ┆            ┆ i64           ┆   ┆         ┆      ┆         ┆      │
╞═══════════════╪═══════════════╪════════════╪═══════════════╪═══╪═════════╪══════╪═════════╪══════╡
│ 1780903193250 ┆ 1780903193442 ┆ 192        ┆ 0             ┆ … ┆ BTCUSDT ┆ BUY  ┆ 0.00008 ┆ true │
│ 1780903193443 ┆ 1780903193554 ┆ 111        ┆ -1            ┆ … ┆ BTCUSDC ┆ SELL ┆ 0.00008 ┆ true │
│ 1780903198458 ┆ 1780903198566 ┆ 108        ┆ 0             ┆ … ┆ BTCUSDT ┆ BUY  ┆ 0.00008 ┆ true │
│ 1780903198566 ┆ 1780903198678 ┆ 112        ┆ -1            ┆ … ┆ BTCUSDC ┆ SELL ┆ 0.00008 ┆ true │
│ 1780903203522 ┆ 1780903203629 ┆ 107        ┆ 0             ┆ … ┆ BTCUSDT ┆ BUY  ┆ 0.00008 ┆ true │
└───────────────┴───────────────┴────────────┴───────────────┴───┴─────────┴──────┴─────────┴──────┘

In [13]:
import os
import time
from binance.client import Client
from binance.exceptions import BinanceAPIException, BinanceOrderException

In [8]:
API_KEY="lghlDGfe8KmFCPhkJk6L6JVmYJVpaazSr2B2YcwZlLymyfTmmWWmayLcJHLtuQZZ"
SECRET_KEY="NFlBmBhkB93jrxI7f7TTQpyazYUNw90RKol9lVhap0wr9yxk5Fqj5cOI3LEAnb8J"

In [9]:
client = Client(API_KEY, SECRET_KEY)
client.API_URL = 'https://demo-api.binance.com/api'

In [12]:
print(client.get_asset_balance(asset='USDT'))
print(client.get_asset_balance(asset='USDC'))
print(client.get_asset_balance(asset='BTC'))

{'asset': 'USDT', 'free': '833.05466978', 'locked': '0.00000000'}
{'asset': 'USDC', 'free': '8752.84416919', 'locked': '0.00000000'}
{'asset': 'BTC', 'free': '0.00138005', 'locked': '0.00000000'}

In [17]:
past_24h = int((time.time() - 24 * 60 * 60) * 1000)

# 3. Fetch and print the raw trades
trades_usdt = client.get_my_trades(symbol="BTCUSDT", startTime=past_24h)
trades_usdc = client.get_my_trades(symbol="BTCUSDC", startTime=past_24h)

In [22]:
df_usdc = pl.DataFrame(trades_usdc)
df_usdt = pl.DataFrame(trades_usdt)

In [23]:
df_usdc.head()

shape: (5, 13)
┌─────────┬──────────┬────────────┬─────────────┬───┬─────────────┬─────────┬─────────┬────────────┐
│ symbol  ┆ id       ┆ orderId    ┆ orderListId ┆ … ┆ time        ┆ isBuyer ┆ isMaker ┆ isBestMatc │
│ ---     ┆ ---      ┆ ---        ┆ ---         ┆   ┆ ---         ┆ ---     ┆ ---     ┆ h          │
│ str     ┆ i64      ┆ i64        ┆ i64         ┆   ┆ i64         ┆ bool    ┆ bool    ┆ ---        │
│         ┆          ┆            ┆             ┆   ┆             ┆         ┆         ┆ bool       │
╞═════════╪══════════╪════════════╪═════════════╪═══╪═════════════╪═════════╪═════════╪════════════╡
│ BTCUSDC ┆ 68898277 ┆ 1897435957 ┆ -1          ┆ … ┆ 17809031935 ┆ false   ┆ false   ┆ true       │
│         ┆          ┆            ┆             ┆   ┆ 66          ┆         ┆         ┆            │
│ BTCUSDC ┆ 68898289 ┆ 1897436657 ┆ -1          ┆ … ┆ 17809031986 ┆ false   ┆ false   ┆ true       │
│         ┆          ┆            ┆             ┆   ┆ 94          ┆         ┆         ┆            │
│ BTCUSDC ┆ 68898304 ┆ 1897437382 ┆ -1          ┆ … ┆ 17809032037 ┆ false   ┆ false   ┆ true       │
│         ┆          ┆            ┆             ┆   ┆ 52          ┆         ┆         ┆            │
│ BTCUSDC ┆ 68898341 ┆ 1897438378 ┆ -1          ┆ … ┆ 17809032092 ┆ false   ┆ false   ┆ true       │
│         ┆          ┆            ┆             ┆   ┆ 56          ┆         ┆         ┆            │
│ BTCUSDC ┆ 68898357 ┆ 1897439184 ┆ -1          ┆ … ┆ 17809032142 ┆ false   ┆ false   ┆ true       │
│         ┆          ┆            ┆             ┆   ┆ 85          ┆         ┆         ┆            │
└─────────┴──────────┴────────────┴─────────────┴───┴─────────────┴─────────┴─────────┴────────────┘

In [24]:
df_usdt.head()

shape: (5, 13)
┌─────────┬───────────┬─────────────┬────────────┬───┬────────────┬─────────┬─────────┬────────────┐
│ symbol  ┆ id        ┆ orderId     ┆ orderListI ┆ … ┆ time       ┆ isBuyer ┆ isMaker ┆ isBestMatc │
│ ---     ┆ ---       ┆ ---         ┆ d          ┆   ┆ ---        ┆ ---     ┆ ---     ┆ h          │
│ str     ┆ i64       ┆ i64         ┆ ---        ┆   ┆ i64        ┆ bool    ┆ bool    ┆ ---        │
│         ┆           ┆             ┆ i64        ┆   ┆            ┆         ┆         ┆ bool       │
╞═════════╪═══════════╪═════════════╪════════════╪═══╪════════════╪═════════╪═════════╪════════════╡
│ BTCUSDT ┆ 236658468 ┆ 40030527311 ┆ -1         ┆ … ┆ 1780903193 ┆ true    ┆ false   ┆ true       │
│         ┆           ┆             ┆            ┆   ┆ 374        ┆         ┆         ┆            │
│ BTCUSDT ┆ 236658492 ┆ 40030539819 ┆ -1         ┆ … ┆ 1780903198 ┆ true    ┆ false   ┆ true       │
│         ┆           ┆             ┆            ┆   ┆ 581        ┆         ┆         ┆            │
│ BTCUSDT ┆ 236658563 ┆ 40030552413 ┆ -1         ┆ … ┆ 1780903203 ┆ true    ┆ false   ┆ true       │
│         ┆           ┆             ┆            ┆   ┆ 645        ┆         ┆         ┆            │
│ BTCUSDT ┆ 236658614 ┆ 40030567884 ┆ -1         ┆ … ┆ 1780903209 ┆ true    ┆ false   ┆ true       │
│         ┆           ┆             ┆            ┆   ┆ 149        ┆         ┆         ┆            │
│ BTCUSDT ┆ 236658652 ┆ 40030580622 ┆ -1         ┆ … ┆ 1780903214 ┆ true    ┆ false   ┆ true       │
│         ┆           ┆             ┆            ┆   ┆ 178        ┆         ┆         ┆            │
└─────────┴───────────┴─────────────┴────────────┴───┴────────────┴─────────┴─────────┴────────────┘