In [34]:
import polars as pl
from polars import col
pl.Config.set_tbl_rows(100)

polars.config.Config

In [19]:
quote_pattern = r"(USDT|BUSD|USDC|EUR|USD|BTC|ETH)$"

In [42]:
df = pl.read_ndjson("../datalake/ingest_20260610_181650.jsonl").slice(1)\
    .with_columns(col("log_ts_utc_ms").cast(pl.Datetime("ms")).alias("datetime"))\
    .select('datetime', 'symbol', 'last_update_id', 'best_bid', 'best_bid_qty', 'best_ask', 'best_ask_qty')
   
    #.with_columns([ col("symbol").str.extract(quote_pattern, 1).alias("qoute"), col("symbol").str.replace(quote_pattern, "").alias("base")])

In [43]:
df.head()

shape: (5, 7)
┌──────────────┬─────────┬────────────────┬──────────┬──────────────┬──────────┬──────────────┐
│ datetime     ┆ symbol  ┆ last_update_id ┆ best_bid ┆ best_bid_qty ┆ best_ask ┆ best_ask_qty │
│ ---          ┆ ---     ┆ ---            ┆ ---      ┆ ---          ┆ ---      ┆ ---          │
│ datetime[ms] ┆ str     ┆ i64            ┆ f64      ┆ f64          ┆ f64      ┆ f64          │
╞══════════════╪═════════╪════════════════╪══════════╪══════════════╪══════════╪══════════════╡
│ 2026-06-10   ┆ BTCUSDT ┆ 95560656175    ┆ 61979.2  ┆ 3.2772       ┆ 61979.21 ┆ 0.01514      │
│ 18:16:51.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ ETHUSDT ┆ 77345351226    ┆ 1630.76  ┆ 58.9243      ┆ 1630.77  ┆ 0.5185       │
│ 18:16:51.033 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BNBUSDT ┆ 19826549795    ┆ 589.63   ┆ 23.316       ┆ 589.64   ┆ 0.027        │
│ 18:16:51.124 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ LINKEUR ┆ 1056342788     ┆ 6.632    ┆ 5.4          ┆ 6.635    ┆ 5.4          │
│ 18:16:51.154 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ SUIUSDT ┆ 15465481348    ┆ 0.7395   ┆ 4690.9       ┆ 0.7396   ┆ 38.8         │
│ 18:16:51.254 ┆         ┆                ┆          ┆              ┆          ┆              │
└──────────────┴─────────┴────────────────┴──────────┴──────────────┴──────────┴──────────────┘

In [44]:
df.filter(col('symbol').is_in(["BTCUSDT","BTCEUR","EURUSDT"])).head(20)

shape: (20, 7)
┌──────────────┬─────────┬────────────────┬──────────┬──────────────┬──────────┬──────────────┐
│ datetime     ┆ symbol  ┆ last_update_id ┆ best_bid ┆ best_bid_qty ┆ best_ask ┆ best_ask_qty │
│ ---          ┆ ---     ┆ ---            ┆ ---      ┆ ---          ┆ ---      ┆ ---          │
│ datetime[ms] ┆ str     ┆ i64            ┆ f64      ┆ f64          ┆ f64      ┆ f64          │
╞══════════════╪═════════╪════════════════╪══════════╪══════════════╪══════════╪══════════════╡
│ 2026-06-10   ┆ BTCUSDT ┆ 95560656175    ┆ 61979.2  ┆ 3.2772       ┆ 61979.21 ┆ 0.01514      │
│ 18:16:51.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316131787    ┆ 53619.57 ┆ 0.051        ┆ 53619.58 ┆ 0.0053       │
│ 18:16:51.723 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560658429    ┆ 61985.99 ┆ 1.68088      ┆ 61986.0  ┆ 0.20923      │
│ 18:16:52.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316131800    ┆ 53619.57 ┆ 0.051        ┆ 53619.58 ┆ 0.0053       │
│ 18:16:52.725 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560659000    ┆ 61987.99 ┆ 1.54501      ┆ 61988.0  ┆ 0.24047      │
│ 18:16:53.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316131836    ┆ 53619.59 ┆ 0.0126       ┆ 53619.6  ┆ 0.0126       │
│ 18:16:53.741 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560659209    ┆ 61987.99 ┆ 1.55892      ┆ 61988.0  ┆ 0.23849      │
│ 18:16:54.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316131842    ┆ 53619.59 ┆ 0.0126       ┆ 53619.6  ┆ 0.0179       │
│ 18:16:54.732 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560659330    ┆ 61987.99 ┆ 1.56902      ┆ 61988.0  ┆ 0.2207       │
│ 18:16:55.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316131844    ┆ 53619.59 ┆ 0.0126       ┆ 53619.6  ┆ 0.0179       │
│ 18:16:55.723 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560659667    ┆ 61987.99 ┆ 1.68673      ┆ 61988.0  ┆ 0.19551      │
│ 18:16:56.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316131889    ┆ 53622.59 ┆ 0.0126       ┆ 53622.6  ┆ 0.0179       │
│ 18:16:56.723 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560659923    ┆ 61987.99 ┆ 1.8939       ┆ 61988.0  ┆ 0.19533      │
│ 18:16:57.033 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560660155    ┆ 61987.99 ┆ 1.89399      ┆ 61988.0  ┆ 0.19011      │
│ 18:16:58.036 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316131946    ┆ 53617.22 ┆ 0.0126       ┆ 53617.23 ┆ 0.0126       │
│ 18:16:58.724 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560660762    ┆ 61987.99 ┆ 1.09528      ┆ 61988.0  ┆ 0.90923      │
│ 18:16:59.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316132044    ┆ 53610.17 ┆ 0.00014      ┆ 53610.18 ┆ 0.0179       │
│ 18:16:59.722 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560662692    ┆ 61982.2  ┆ 0.00155      ┆ 61982.21 ┆ 2.1094       │
│ 18:17:00.032 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCEUR  ┆ 10316132076    ┆ 53610.17 ┆ 0.01274      ┆ 53610.18 ┆ 0.02597      │
│ 18:17:00.723 ┆         ┆                ┆          ┆              ┆          ┆              │
│ 2026-06-10   ┆ BTCUSDT ┆ 95560663012    ┆ 61982.2  ┆ 0.00314      ┆ 61982.21 ┆ 2.13292      │
│ 18:17:01.032 ┆         ┆                ┆          ┆              ┆          ┆              │
└──────────────┴─────────┴────────────────┴──────────┴──────────────┴──────────┴──────────────┘

In [45]:
df.filter(col('symbol').is_in(["EURUSDT"])).head(20)

shape: (0, 7)
┌──────────────┬────────┬────────────────┬──────────┬──────────────┬──────────┬──────────────┐
│ datetime     ┆ symbol ┆ last_update_id ┆ best_bid ┆ best_bid_qty ┆ best_ask ┆ best_ask_qty │
│ ---          ┆ ---    ┆ ---            ┆ ---      ┆ ---          ┆ ---      ┆ ---          │
│ datetime[ms] ┆ str    ┆ i64            ┆ f64      ┆ f64          ┆ f64      ┆ f64          │
╞══════════════╪════════╪════════════════╪══════════╪══════════════╪══════════╪══════════════╡
└──────────────┴────────┴────────────────┴──────────┴──────────────┴──────────┴──────────────┘