In [1]:
!uv pip install altair

Audited 1 package in 22ms

In [2]:
import polars as pl
from polars import col


pl.Config.set_tbl_rows(1000)      # Allow rendering up to 1000 rows inline
pl.Config.set_tbl_cols(20)        # Allow rendering up to 20 columns wide
pl.Config.set_fmt_str_lengths(50) # Prevent text strings from getting cropped

market_response_path = "/Users/oceansxyz/alphanode-metal/logs/market/market_20260614_105506.jsonl"

#### Load JSONL

In [3]:
#Raw binance reponse for market web socket - pretty much a static
book_ticker_schema = pl.Struct([
    pl.Field("ts", pl.Int64),
    pl.Field("frame", pl.Struct([
        pl.Field("u", pl.Int64),
        pl.Field("s", pl.String),
        pl.Field("b", pl.String),
        pl.Field("B", pl.String),
        pl.Field("a", pl.String),
        pl.Field("A", pl.String),
    ])),
])

with open(market_response_path) as f:
    metadata_json = f.readline().strip()
    print("Metadata Raw Line:", metadata_json)
    df_market = (
        pl.read_csv(
            f,
            has_header=False,
            new_columns=["json_str"],
            separator="\n",
            infer_schema=False,
        )
        .select(pl.col("json_str").str.json_decode(dtype=book_ticker_schema))
        .unnest("json_str")
        .unnest("frame")
        .with_columns([
            pl.col("u").cast(pl.Int64),
            pl.col("s"),
            pl.col("b").cast(pl.Float64),
            pl.col("B").cast(pl.Float64),
            pl.col("a").cast(pl.Float64),
            pl.col("A").cast(pl.Float64),
        ])
    )


# Select relevant cols for alpha calulation with identifiable file names
market_rates = df_market.select(
    col("ts"), col("s").alias("symbol"), col("b").alias("bid"), col("a").alias("ask")
)

# duration of web socket listen
min_ts = market_rates.min().select("ts").item()
max_ts = market_rates.max().select("ts").item()
duration_m =(max_ts-min_ts)/60000


print(f"Duration of listen : {duration_m} mins")
print(market_rates.group_by("symbol").len())

Metadata Raw Line: {"ts":1781434506715,"frame":{"result":null,"id":1}}
Duration of listen : 9.4146 mins
shape: (3, 2)
┌──────────┬──────┐
│ symbol   ┆ len  │
│ ---      ┆ ---  │
│ str      ┆ u32  │
╞══════════╪══════╡
│ BTCEURI  ┆ 115  │
│ EURIUSDT ┆ 8    │
│ BTCUSDT  ┆ 2966 │
└──────────┴──────┘

In [4]:
## Split dataframe symbolwise symbol is an orderbook
symbol_0 = market_rates.filter(col("symbol")=="BTCUSDT").select(["ts", col("bid").alias("BTCUSDT_bid"), col("ask").alias("BTCUSDT_ask")])
symbol_1 = market_rates.filter(col("symbol")=="BTCEURI").select(["ts", col("bid").alias("BTCEURI_bid"), col("ask").alias("BTCEURI_ask")])
symbol_2 = market_rates.filter(col("symbol")=="EURIUSDT").select(["ts", col("bid").alias("EURIUSDT_bid"), col("ask").alias("EURIUSDT_ask")])

In [5]:
# Forward fill missing values by copying the last known valid price down 
# for all generated ticker metrics simultaneously, skipping the timestamp.
market_rates_widened = symbol_0.join(symbol_1, on="ts", how="full", coalesce=True)\
    .join(symbol_2, on="ts", how="full", coalesce=True)\
    .sort("ts")\
    .select([
        col("ts"),
        col("*").exclude("ts").fill_null(strategy="forward")
    ]).drop_nulls()

market_rates_widened.head()

shape: (5, 7)
┌──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ ts           ┆ BTCUSDT_bid ┆ BTCUSDT_ask ┆ BTCEURI_bid ┆ BTCEURI_ask ┆ EURIUSDT_bi ┆ EURIUSDT_as │
│ ---          ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ d           ┆ k           │
│ i64          ┆ f64         ┆ f64         ┆ f64         ┆ f64         ┆ ---         ┆ ---         │
│              ┆             ┆             ┆             ┆             ┆ f64         ┆ f64         │
╞══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 178143466627 ┆ 64531.44    ┆ 64531.45    ┆ 55825.34    ┆ 55847.46    ┆ 1.1556      ┆ 1.1559      │
│ 7            ┆             ┆             ┆             ┆             ┆             ┆             │
│ 178143466659 ┆ 64531.44    ┆ 64531.45    ┆ 55825.34    ┆ 55847.46    ┆ 1.1556      ┆ 1.1559      │
│ 0            ┆             ┆             ┆             ┆             ┆             ┆             │
│ 178143466678 ┆ 64531.44    ┆ 64531.45    ┆ 55825.34    ┆ 55847.46    ┆ 1.1556      ┆ 1.1559      │
│ 1            ┆             ┆             ┆             ┆             ┆             ┆             │
│ 178143466733 ┆ 64531.44    ┆ 64531.45    ┆ 55825.34    ┆ 55847.46    ┆ 1.1556      ┆ 1.1559      │
│ 8            ┆             ┆             ┆             ┆             ┆             ┆             │
│ 178143466758 ┆ 64531.44    ┆ 64531.45    ┆ 55825.34    ┆ 55847.46    ┆ 1.1556      ┆ 1.1559      │
│ 7            ┆             ┆             ┆             ┆             ┆             ┆             │
└──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

##### Notation & Model

NODE_0 = USDT NODE_1 = BTC NODE_2 = EURI  

EDGE_0 = BTCUSDT  EDGE_1 = BTCEURI  EDGE_2 = EURIUSDT  

Clockwise Walk  0→1  →1→2  →2→0  

BUY  BTCUSDT  @ASK  === 0→1  
SELL BTCEURI  @BID  === 1→2  
SELL EURIUSDT @BID  === 2→0

#### Clockwise Walk  0→1  →1→2  →2→0

In [8]:
clockwise_walk = market_rates_widened.select("ts", col("BTCUSDT_ask"), "BTCEURI_bid", "EURIUSDT_bid")\
    .unique(subset=["BTCUSDT_ask", "BTCEURI_bid", "EURIUSDT_bid"])\
    .with_columns((col("BTCEURI_bid")*col("EURIUSDT_bid")).alias("BTCEURIUSDT_bid"))\
    .with_columns((col("BTCEURIUSDT_bid")-col("BTCUSDT_ask")).abs().alias("alpha"))

clockwise_walk.sort("alpha", descending=True)

shape: (193, 6)
┌───────────────┬─────────────┬─────────────┬──────────────┬─────────────────┬───────────┐
│ ts            ┆ BTCUSDT_ask ┆ BTCEURI_bid ┆ EURIUSDT_bid ┆ BTCEURIUSDT_bid ┆ alpha     │
│ ---           ┆ ---         ┆ ---         ┆ ---          ┆ ---             ┆ ---       │
│ i64           ┆ f64         ┆ f64         ┆ f64          ┆ f64             ┆ f64       │
╞═══════════════╪═════════════╪═════════════╪══════════════╪═════════════════╪═══════════╡
│ 1781435059590 ┆ 64492.0     ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 47.204116 │
│ 1781435059589 ┆ 64491.99    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 47.194116 │
│ 1781435059589 ┆ 64491.36    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 46.564116 │
│ 1781435059589 ┆ 64490.82    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 46.024116 │
│ 1781435059589 ┆ 64490.53    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 45.734116 │
│ 1781435059589 ┆ 64490.51    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 45.714116 │
│ 1781435059589 ┆ 64490.49    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 45.694116 │
│ 1781435059589 ┆ 64490.39    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 45.594116 │
│ 1781434871598 ┆ 64517.9     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 45.519944 │
│ 1781435059589 ┆ 64489.9     ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 45.104116 │
│ 1781435058599 ┆ 64489.89    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 45.094116 │
│ 1781435058599 ┆ 64489.53    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 44.734116 │
│ 1781435058599 ┆ 64489.52    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 44.724116 │
│ 1781435058599 ┆ 64488.96    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 44.164116 │
│ 1781435058599 ┆ 64488.74    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.944116 │
│ 1781435058599 ┆ 64488.73    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.934116 │
│ 1781435058599 ┆ 64488.72    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.924116 │
│ 1781435058599 ┆ 64488.71    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.914116 │
│ 1781435058599 ┆ 64488.65    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.854116 │
│ 1781435058599 ┆ 64488.56    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.764116 │
│ 1781435058598 ┆ 64488.55    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.754116 │
│ 1781435058598 ┆ 64487.82    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.024116 │
│ 1781435058598 ┆ 64487.81    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 43.014116 │
│ 1781434922597 ┆ 64515.23    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 42.849944 │
│ 1781435058598 ┆ 64487.5     ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 42.704116 │
│ 1781435058598 ┆ 64487.34    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 42.544116 │
│ 1781435058598 ┆ 64487.17    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 42.374116 │
│ 1781435058598 ┆ 64487.1     ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 42.304116 │
│ 1781435058598 ┆ 64487.08    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 42.284116 │
│ 1781435058598 ┆ 64486.49    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 41.694116 │
│ 1781435058598 ┆ 64486.45    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 41.654116 │
│ 1781435058598 ┆ 64486.44    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 41.644116 │
│ 1781435058598 ┆ 64486.41    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 41.614116 │
│ 1781435058598 ┆ 64486.31    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 41.514116 │
│ 1781435058598 ┆ 64486.19    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 41.394116 │
│ 1781435058598 ┆ 64486.18    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 41.384116 │
│ 1781435058598 ┆ 64485.78    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 40.984116 │
│ 1781435058598 ┆ 64485.72    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 40.924116 │
│ 1781435058598 ┆ 64485.23    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 40.434116 │
│ 1781435058598 ┆ 64485.22    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 40.424116 │
│ 1781435058598 ┆ 64484.39    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 39.594116 │
│ 1781434929594 ┆ 64511.81    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 39.429944 │
│ 1781435058598 ┆ 64484.01    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 39.214116 │
│ 1781435058598 ┆ 64484.0     ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 39.204116 │
│ 1781435058598 ┆ 64483.93    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 39.134116 │
│ 1781434871598 ┆ 64511.47    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 39.089944 │
│ 1781434855661 ┆ 64511.46    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 39.079944 │
│ 1781434855661 ┆ 64511.45    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 39.069944 │
│ 1781435058598 ┆ 64483.86    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 39.064116 │
│ 1781434855661 ┆ 64511.33    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 38.949944 │
│ 1781435058598 ┆ 64483.71    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 38.914116 │
│ 1781434855661 ┆ 64511.03    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 38.649944 │
│ 1781434855661 ┆ 64510.9     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 38.519944 │
│ 1781434855661 ┆ 64510.87    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 38.489944 │
│ 1781435058598 ┆ 64483.28    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 38.484116 │
│ 1781434855661 ┆ 64510.67    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 38.289944 │
│ 1781435058598 ┆ 64483.08    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 38.284116 │
│ 1781435058598 ┆ 64483.07    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 38.274116 │
│ 1781435058598 ┆ 64483.06    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 38.264116 │
│ 1781435058598 ┆ 64482.81    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 38.014116 │
│ 1781434855661 ┆ 64510.29    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 37.909944 │
│ 1781434851596 ┆ 64510.28    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 37.899944 │
│ 1781434851596 ┆ 64510.27    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 37.889944 │
│ 1781434851595 ┆ 64510.11    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 37.729944 │
│ 1781434851595 ┆ 64510.0     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 37.619944 │
│ 1781434851595 ┆ 64509.89    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 37.509944 │
│ 1781434851595 ┆ 64509.51    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 37.129944 │
│ 1781435038299 ┆ 64479.96    ┆ 55765.94    ┆ 1.1556       ┆ 64443.120264    ┆ 36.839736 │
│ 1781434851595 ┆ 64509.1     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 36.719944 │
│ 1781435058598 ┆ 64481.36    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 36.564116 │
│ 1781434930604 ┆ 64508.78    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 36.399944 │
│ 1781434851595 ┆ 64508.63    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 36.249944 │
│ 1781435058598 ┆ 64480.82    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 36.024116 │
│ 1781434851595 ┆ 64508.4     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 36.019944 │
│ 1781435058598 ┆ 64480.81    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 36.014116 │
│ 1781435058598 ┆ 64479.98    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 35.184116 │
│ 1781435058598 ┆ 64479.97    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 35.174116 │
│ 1781435038299 ┆ 64479.96    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 35.164116 │
│ 1781435058598 ┆ 64479.95    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 35.154116 │
│ 1781435058597 ┆ 64479.86    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 35.064116 │
│ 1781435058597 ┆ 64479.85    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 35.054116 │
│ 1781435058597 ┆ 64479.74    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 34.944116 │
│ 1781434851595 ┆ 64507.24    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.859944 │
│ 1781434850597 ┆ 64507.23    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.849944 │
│ 1781434850597 ┆ 64507.22    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.839944 │
│ 1781434850597 ┆ 64507.21    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.829944 │
│ 1781434850597 ┆ 64507.17    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.789944 │
│ 1781434850597 ┆ 64506.56    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.179944 │
│ 1781434850597 ┆ 64506.54    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.159944 │
│ 1781434850597 ┆ 64506.47    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.089944 │
│ 1781434850597 ┆ 64506.46    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 34.079944 │
│ 1781434850597 ┆ 64505.87    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 33.489944 │
│ 1781434850597 ┆ 64505.77    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 33.389944 │
│ 1781434850597 ┆ 64505.76    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 33.379944 │
│ 1781435038597 ┆ 64478.01    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 33.214116 │
│ 1781434931593 ┆ 64505.38    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 32.999944 │
│ 1781434850596 ┆ 64504.64    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 32.259944 │
│ 1781434849598 ┆ 64504.63    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 32.249944 │
│ 1781434849598 ┆ 64504.62    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 32.239944 │
│ 1781435058597 ┆ 64476.64    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 31.844116 │
│ 1781435040599 ┆ 64476.63    ┆ 55767.39    ┆ 1.1556       ┆ 64444.795884    ┆ 31.834116 │
│ 1781434849598 ┆ 64504.1     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 31.719944 │
│ 1781434849598 ┆ 64504.09    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 31.709944 │
│ 1781434849598 ┆ 64504.01    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 31.629944 │
│ 1781434849598 ┆ 64504.0     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 31.619944 │
│ 1781434849598 ┆ 64503.7     ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 31.319944 │
│ 1781434849598 ┆ 64503.24    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 30.859944 │
│ 1781434849598 ┆ 64503.23    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 30.849944 │
│ 1781434849598 ┆ 64502.48    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 30.099944 │
│ 1781434837282 ┆ 64500.01    ┆ 55789.52    ┆ 1.1556       ┆ 64470.369312    ┆ 29.640688 │
│ 1781434849598 ┆ 64500.02    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 27.639944 │
│ 1781434837301 ┆ 64500.01    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 27.629944 │
│ 1781435021591 ┆ 64496.59    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 24.209944 │
│ 1781434837109 ┆ 64500.01    ┆ 55789.52    ┆ 1.1557       ┆ 64475.948264    ┆ 24.061736 │
│ 1781434837109 ┆ 64500.01    ┆ 55789.53    ┆ 1.1557       ┆ 64475.959821    ┆ 24.050179 │
│ 1781435026590 ┆ 64492.93    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 20.549944 │
│ 1781434666277 ┆ 64531.45    ┆ 55825.34    ┆ 1.1556       ┆ 64511.762904    ┆ 19.687096 │
│ 1781435028595 ┆ 64492.01    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 19.629944 │
│ 1781434775299 ┆ 64528.66    ┆ 55823.26    ┆ 1.1556       ┆ 64509.359256    ┆ 19.300744 │
│ 1781434761597 ┆ 64528.66    ┆ 55825.34    ┆ 1.1556       ┆ 64511.762904    ┆ 16.897096 │
│ 1781434829285 ┆ 64500.01    ┆ 55823.26    ┆ 1.1557       ┆ 64514.941582    ┆ 14.931582 │
│ 1781434798592 ┆ 64521.13    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 11.08894  │
│ 1781434798592 ┆ 64521.12    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 11.07894  │
│ 1781434798592 ┆ 64521.05    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 11.00894  │
│ 1781434798592 ┆ 64520.72    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 10.67894  │
│ 1781434798591 ┆ 64520.7     ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 10.65894  │
│ 1781434798591 ┆ 64520.38    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 10.33894  │
│ 1781434798591 ┆ 64520.03    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 9.98894   │
│ 1781434798591 ┆ 64520.02    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 9.97894   │
│ 1781434798591 ┆ 64520.01    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 9.96894   │
│ 1781435038299 ┆ 64479.96    ┆ 55789.51    ┆ 1.1556       ┆ 64470.357756    ┆ 9.602244  │
│ 1781434798591 ┆ 64519.52    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 9.47894   │
│ 1781434826591 ┆ 64500.01    ┆ 55823.26    ┆ 1.1556       ┆ 64509.359256    ┆ 9.349256  │
│ 1781434798591 ┆ 64519.05    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 9.00894   │
│ 1781434798591 ┆ 64518.81    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 8.76894   │
│ 1781434775596 ┆ 64517.91    ┆ 55823.26    ┆ 1.1556       ┆ 64509.359256    ┆ 8.550744  │
│ 1781434798591 ┆ 64518.59    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 8.54894   │
│ 1781434798591 ┆ 64518.55    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 8.50894   │
│ 1781434798591 ┆ 64518.11    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 8.06894   │
│ 1781434798591 ┆ 64518.1     ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 8.05894   │
│ 1781434798591 ┆ 64518.01    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 7.96894   │
│ 1781434798591 ┆ 64517.94    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 7.89894   │
│ 1781434798591 ┆ 64517.93    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 7.88894   │
│ 1781434798590 ┆ 64517.92    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 7.87894   │
│ 1781434778294 ┆ 64517.91    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 7.86894   │
│ 1781435035601 ┆ 64479.96    ┆ 55791.26    ┆ 1.1556       ┆ 64472.380056    ┆ 7.579944  │
│ 1781434812299 ┆ 64516.69    ┆ 55823.26    ┆ 1.1556       ┆ 64509.359256    ┆ 7.330744  │
│ 1781434811599 ┆ 64516.69    ┆ 55823.85    ┆ 1.1556       ┆ 64510.04106     ┆ 6.64894   │
│ 1781434814303 ┆ 64504.01    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 5.51104   │
│ 1781434814597 ┆ 64504.02    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 5.50104   │
│ 1781434814598 ┆ 64504.03    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 5.49104   │
│ 1781434812602 ┆ 64504.01    ┆ 55823.26    ┆ 1.1556       ┆ 64509.359256    ┆ 5.349256  │
│ 1781434814598 ┆ 64504.98    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.54104   │
│ 1781434814598 ┆ 64505.0     ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.52104   │
│ 1781434814598 ┆ 64505.01    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.51104   │
│ 1781434814598 ┆ 64505.02    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.50104   │
│ 1781434814598 ┆ 64505.03    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.49104   │
│ 1781434814598 ┆ 64505.04    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.48104   │
│ 1781434814598 ┆ 64505.05    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.47104   │
│ 1781434814598 ┆ 64505.06    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.46104   │
│ 1781434814598 ┆ 64505.16    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 4.36104   │
│ 1781434814598 ┆ 64505.84    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 3.68104   │
│ 1781434814598 ┆ 64505.87    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 3.65104   │
│ 1781434822594 ┆ 64505.77    ┆ 55823.26    ┆ 1.1556       ┆ 64509.359256    ┆ 3.589256  │
│ 1781434814598 ┆ 64505.94    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 3.58104   │
│ 1781434814598 ┆ 64505.99    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 3.53104   │
│ 1781434814599 ┆ 64506.0     ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 3.52104   │
│ 1781434814599 ┆ 64506.01    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 3.51104   │
│ 1781434814599 ┆ 64506.45    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 3.07104   │
│ 1781434814599 ┆ 64506.78    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 2.74104   │
│ 1781434814599 ┆ 64507.23    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 2.29104   │
│ 1781434814599 ┆ 64507.24    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 2.28104   │
│ 1781434814600 ┆ 64507.29    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 2.23104   │
│ 1781434814602 ┆ 64511.64    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 2.11896   │
│ 1781434821444 ┆ 64511.47    ┆ 55823.26    ┆ 1.1556       ┆ 64509.359256    ┆ 2.110744  │
│ 1781434814600 ┆ 64507.44    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 2.08104   │
│ 1781434814603 ┆ 64511.47    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 1.94896   │
│ 1781434814600 ┆ 64507.59    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 1.93104   │
│ 1781434821445 ┆ 64511.47    ┆ 55823.48    ┆ 1.1556       ┆ 64509.613488    ┆ 1.856512  │
│ 1781434815295 ┆ 64511.47    ┆ 55823.49    ┆ 1.1556       ┆ 64509.625044    ┆ 1.844956  │
│ 1781434814600 ┆ 64508.01    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 1.51104   │
│ 1781434814600 ┆ 64508.4     ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 1.12104   │
│ 1781434814600 ┆ 64508.56    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.96104   │
│ 1781434814601 ┆ 64510.47    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.94896   │
│ 1781434814601 ┆ 64510.4     ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.87896   │
│ 1781434814601 ┆ 64510.35    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.82896   │
│ 1781434814600 ┆ 64510.09    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.56896   │
│ 1781434814600 ┆ 64510.05    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.52896   │
│ 1781434814600 ┆ 64510.02    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.49896   │
│ 1781434814600 ┆ 64509.96    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.43896   │
│ 1781434814600 ┆ 64509.95    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.42896   │
│ 1781434814600 ┆ 64509.15    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.37104   │
│ 1781434814600 ┆ 64509.39    ┆ 55823.4     ┆ 1.1556       ┆ 64509.52104     ┆ 0.13104   │
└───────────────┴─────────────┴─────────────┴──────────────┴─────────────────┴───────────┘

In [7]:
clockwise_walk.plot.line(x="ts", y="alpha")

alt.Chart(...)